### PR TITLE
Fix block methods

### LINKED ISSUE #38: Incorrect smbus methods
Currently `LinuxI2CDevice::smbus_process_block` calls `ffi::i2c_smbus_write_i2c_block_data` instead of the real smbus2 ffi method (which doesn't seem to be implemented in `ffi.rs`), and `LinuxI2CDevice::smbus_write_i2c_block_data` doesn't exist as one would expect it to.

`smbus_process_block` presumably needs to be renamed to `smbus_write_i2c_block_data`, and `LinuxI2CDevice::smbus_process_block` added with the proper signature (returning a vec) plus `i2c_smbus_process_call_block` or similar added to the ffi for it to use.

### PR DESCRIPTION
**Pull request by arcnmx**
`process_block` and `write_i2c_block` were mixed up and sort of one was missing.

Fixes #38 

Major breaking change to the api that probably means a 0.4 release.

### CODE REVIEW

File: src/ffi.rs [hunk 1]
```diff
@@ -403,3 +403,29 @@ pub fn i2c_smbus_write_i2c_block_data(fd: RawFd,
...
 }
+
+#[inline]
+pub fn i2c_smbus_process_call_block(fd: RawFd, register: u8, values: &[u8]) -> Result<Vec<u8>, I2CError> {
+    let mut data = i2c_smbus_data::empty();
+    let len: usize = if values.len() > 31 {
+        31
+    } else {
+        values.len()
+    };
```
Comment (posborne) [inline src/ffi.rs]: Perhaps slightly more succinct as `let len = std::cmp::min(values.len(), 31)` but not really any different.

**Comment by posborne** [comment]
> Major breaking change to the api that probably means a 0.4 release.

Agreed.  Shouldn't be a problem to move toward a 0.4 release.
